## use common layer
is_use_common_environment: true

## env
envs:
  - dev
  - stg
  - prd

## projects
projects:
  front:
    - web
    - webview
    - mobile
  backend:
    - core
    - api
  devops:
    - idp
    - backstage
  blanks:
